### ISSUE TITLE
Document that you need to join the bot to your server

### ISSUE THREAD

**Issue by fsckyou** [Awakened-Redstone/AutoWhitelist#11]
### Is your feature request related to a problem? Please describe.

The documentation as it is today does not outline this step. It took a bit of head scratching to figure it out since I'm not a Discord bot developer.

### Describe the solution you'd like

Add that you need to point a browser at the [https://discord.com/api/oauth2/authorize?client_id=<client-id>&scope=bot&permissions=8](https://discord.com/api/oauth2/authorize?client_id=<client-id>&scope=bot&permissions=8) to do this step.

### Describe alternatives you've considered

None.

### Additional context

[https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow](https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow)

**Comment by Awakened-Redstone** [comment]
Oh, sorry, my bad, I forgot to include a tutorial to add the bot to the server, I'm working on it 🙂

**Comment by Awakened-Redstone** [comment]
Added a gif to the documentation, any other issues feel free to open a new issue or if you think I could update the new gif you can reopen and/or reply this issue
