### ISSUE TITLE
GatewayIntent.MESSAGE_CONTENT / Failed to set bot activity

### ISSUE THREAD

**Issue by Tikkle** [Awakened-Redstone/AutoWhitelist#12]
### Version information

1.1.2

### Expected Behavior

**Message Content**
No error about Message Content Intent since it is enabled in the Bot and a working bot

**Activity Status**
No error about setting activity and a working bot

### Actual Behavior

**Message Content**
Error about Message Content Intent and the bot ceases to work.
[Log](https://hastebin.com/enaqakijad.kotlin)

**Activity Status**
Error about setting activity status and bot ceases to work.
[Log](https://hastebin.com/utokigudej.sql)

### Reproduction Steps

**For both issues**
1. Install Mod
2. Setup Bot according to Modrinth page instructions
3. restart server, observe error, and bot not working

### Java version

Java 17

**Comment by Awakened-Redstone** [comment]
Oh, seems that discord did dome changes to the intents, I'll update the documentation. On the bot page there should be a message intent toggle or something similar.

I'll also work on slash commands support too to avoid future issues with discord enforcing them

**Comment by Awakened-Redstone** [comment]
I gave a look at the documentation and everything should be right, please make sure that you enable this option
![image](https://user-images.githubusercontent.com/40528665/192905629-a7649e37-c6ab-4184-b9eb-c48ba3a3f270.png)

An update supporting slash commands will still be done tho.

**Comment by Tikkle** [comment]
No worries, i do have the Message Content Intent enabled, but the mod/bot still seems to not work.

Here is a list of my mods/datapacks if you want to recreate my issue:

**Mods:**
Alternate Current, Armor Stand Editor, AutoWhitelist, Cloth Config, dcintegration (discord chat+mc chat), fabic api, fabric kotlin, ferritecore, krypton, lazydfu, lithium, midnightlib, nochatreports, repurposed structures, sessility, simply no report, starlight, timeoutout, wither-cage-fix

**Datapacks:**
BlazeandCaves Advancements Pack 1.15.zip, anti enderman grief v1.1.3.zip, custom nether portals v2.3.6.zip, double shulker shells v1.3.3.zip, more mob heads v2.10.1.zip, name colors v1.0.1.zip, nether portal coords v1.1.3.zip, silence mobs v1.1.3.zip, unlock all recipes v2.0.4.zip, villager workstation highlights v1.1.3.zip

**Comment by Awakened-Redstone** [comment]
I could not reproduce the error. have you used a previous version of the mod before?
Also, the activity status should not impact on the bot performance.
Do you mind sharing your configurations? Make **SURE** to remove the token if you share it

**Comment by Tikkle** [comment]
I think i removed it correctly:

https://hastebin.com/nonajexesu.json
https://hastebin.com/emiluyuvuw.json

**Comment by Awakened-Redstone** [comment]
dcintegration seems to use the same library as AutoWhitelist, and the version it uses seems to be overriding the version my mod uses, I'll try to work on an update to fix the compatibility issue

**Comment by Awakened-Redstone** [comment]
I'm having some issues updating the mod and might have to finish updating tomorrow, I'll notify you when the update is ready

**Comment by Awakened-Redstone** [comment]
I made a compatibility version, since the mod is targeted to be as stable as possible and the compat version uses a JDA beta it doesn't fit in Modrinth so I published it on [Github](https://github.com/Awakened-Redstone/AutoWhitelist/releases/tag/1.1.2-compat-dcintegration.2.4.7)
