### ISSUE TITLE
[Bug]: Bot isn't responding to messages sent in a thread

### ISSUE THREAD

**Issue by lmore377** [Awakened-Redstone/AutoWhitelist#19]
### Version information

1.1.5

### Version type

Lite

### Expected Behavior

The mod should respond when sending a command in a thread.

### Actual Behavior

The bot just doesn't see the message at all.

### Reproduction Steps

Just make a thread and try sending a command there lol

### Java version

Java 17

### Additional information

The bot is able to see messages that are sent in the parent channel of the thread so I don't think it's a permission issue.

**Comment by Awakened-Redstone** [comment]
The current version of the library I'm using doesn't seem to support it, currently only the beta versions of it has support for that, AutoWhitelist full should soon be approved on Modrinth and that uses a newer version
It will be available at https://modrinth.com/mod/autowhitelist when approved

**Comment by Awakened-Redstone** [comment]
This issue will be fixed once #25 is completed and closed, for versions 1.19.4 and newer a working version is available at   https://modrinth.com/mod/autowhitelist
