### ISSUE TITLE
[Bug]: LuckPerms node not saved

### ISSUE THREAD

**Issue by 7coil** [Awakened-Redstone/AutoWhitelist#20]
### Version information

1.0.0-alpha.1

### Version type

Full

### Expected Behavior

As a user, when I run `np!register` as a certain Discord role, I would like a LuckPerms group assigned to me

### Actual Behavior

The end user is not assigned the LuckPerms group

## Configuration Setup
```json5
"entries": [
    {
        "roleIds": [
            "// the copied role id //"
        ],
        "type": "LUCKPERMS_GROUP",
        "group": "twitch_subscriber"
    }
}
```

## Discord Steps

1. `np!register 7coil`
2. Bot replies with "Welcome to the group!"
3. User added to the whitelist, but given the default Luckperms permissions

### Java version

17

### Additional information

In line 29 of `LuckpermsEntry.java`, you are not calling `UserManager#saveUser(User user)`
https://github.com/Awakened-Redstone/AutoWhitelist/blob/c559c275a3473bcc59b7575f314ceb70c11bc81d/src/main/java/com/awakenedredstone/autowhitelist/config/compat/LuckpermsEntry.java#L29

This is required to save the user into LuckPerms, and give the correct group/permission to the user.

See the LuckPerms documentation for more information.

https://luckperms.net/wiki/Developer-API-Usage#setting-metadata

**Comment by Awakened-Redstone** [comment]
Should be solved with the merge of #21 
Please let me know if the issue persists
As the mod is still on alpha it isn't being heavily tested yet
