### ISSUE TITLE
[Bug]: The server cannot finish rebooting and shutting down

### ISSUE THREAD

**Issue by TRemill** [Awakened-Redstone/AutoWhitelist#22]
### Version information

1.0.0-alpha.3

### Version type

Full

### Expected Behavior

I just wanted to restart the server

### Actual Behavior

The server just freezes in a dead place when it finishes saving worlds

### Reproduction Steps

1. Sent a restart command
2. Tada, the server is just standing

### Java version

19.0.1

### Additional information

By the method of exclusion, it was revealed that it is because of your fashion that this happens. Here is a list of mods that are used on the server:
- autowhitelist-1.0.0-alpha.3
- owo-lib-0.10.3+1.19.4
- mods-command-mc1.19.4-1.1.2
- LuckPerms-Fabric-5.4.66
- fabric-language-kotlin-1.9.4+kotlin.1.8.21
- fabric-api-0.79.0+1.19.4

The server itself runs on Minecraft 1.19.4 with Fabric Loader 0.14.21

**Comment by Awakened-Redstone** [comment]
This seems to be an issue with the library I'm using to run the bot, I'll look into it and open an issue there if needed

**Comment by TRemill** [comment]
I also noticed the same behavior in the lite version.

**Comment by Awakened-Redstone** [comment]
I though I fixed it on the lite version
Oh well, I'll look into it more, I may have to hard stop the bot, hopefully it shouldn't cause any big issues.

**Comment by Awakened-Redstone** [comment]
Fixed on:
* [1.1.6](https://modrinth.com/mod/autowhitelist-lite/versions) for AutoWhitelist Lite
* [1.0.0-aplha.4](https://modrinth.com/mod/autowhitelist/version/1.0.0-alpha.4) for AutoWhitelist
