### ISSUE TITLE
[Documentation]: Differences between Lite and Full

### ISSUE THREAD

**Issue by meza** [Awakened-Redstone/AutoWhitelist#23]
### Version type

Lite

### What on the documentation is being suggested to be changed

I've been struggling to understand what the difference is between the Lite and non-lite version and if I'm using the Lite, can I switch to the full one without any hassle?

### Describe the change

I'd like some information on how to switch to the full version if I've been using the Lite so far. Are there any configuration changes I need to make? Is it a drop-in replacement? Why are they different to begin with?

**Comment by Awakened-Redstone** [comment]
I made some documentation on migrating here https://github.com/Awakened-Redstone/AutoWhitelist/wiki/Migrating-from-Lite-to-Full

I put it together rather quickly so any feedback is appreciated
If you have any question regarding it feel free to ask it

**Comment by Awakened-Redstone** [comment]
I do plan on making the migration easier on the future, but this may take a while for me to have free time for that

**Comment by meza** [comment]
Awesome, thanks! I'll make notes as I go, see if I can help with the migration docs
