### ISSUE TITLE
[New feature]: 1.20.5 & 6 support, along with 1.21 support when it comes out

### ISSUE THREAD

**Issue by cqm3ron** [Awakened-Redstone/AutoWhitelist#28]
### Is your feature request related to a problem? Please describe.

I can't use the mod on my current server!

### Describe the solution you'd like

The mod to be updated to the latest versions, and 1.21 when it eventually releases.

### Describe alternatives you've considered

N/A

**Comment by Awakened-Redstone** [comment]
What version of the mod are you using?

**Comment by cqm3ron** [comment]
The latest version

**Comment by cqm3ron** [comment]
My bad, I somehow didn't see the 1.20.5-6 version that you have already released. I must be blind!

**Comment by Awakened-Redstone** [comment]
Don't worry, the way the publishing is setup is kinda bad rn, with the newer being lower than older versions

**Comment by Awakened-Redstone** [comment]
I also just now set it to show for 1.20.6 as I forgot to do that, and it was as 1.20.5 only

**Comment by cqm3ron** [comment]
Awesome. Is 1.21 support planned when it releases?

**Comment by Awakened-Redstone** [comment]
yes
